[package]
name = "flamewm-shell-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
flamewm-api = { path = "../flamewm-api" }
flamewm-platform = { path = "../flamewm-platform" }
flamewm-ui-core = { path = "../flamewm-ui-core" }

[lints]
workspace = true
