[package]
name = "flamewm-wm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
flamewm-wm-x11 = { path = "../flamewm-wm-x11" }
flamewm-api = { path = "../flamewm-api" }
flamewm-session-core = { path = "../flamewm-session-core" }
flamewm-xsettings = { path = "../flamewm-xsettings" }

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "flamewm"
path = "src/main.rs"
