[package]
name = "flamewm-x11-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
flamewm-api = { path = "../flamewm-api" }
flamewm-applications = { path = "../flamewm-applications" }
x11rb.workspace = true

[lints]
workspace = true
