[package]
name = "text-editor"
publish = false
version.workspace = true
edition.workspace = true

[dependencies]
creamui-core = { workspace = true }
creamui-jsx = { workspace = true }
creamui-macros = { workspace = true }
creamui-reactive = { workspace = true }
creamui-render = { workspace = true }
creamui-theme = { workspace = true }
creamui-widgets = { workspace = true }
rfd = { version = "0.17", default-features = false, features = ["xdg-portal"] }
