[package]
name = "rustwebrender-x11"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Minimal native X11 backend for RustWebRender"

[dependencies]
rustwebrender-core = { path = "../rustwebrender-core" }

[lib]
path = "src/lib.rs"

[[bin]]
name = "rwr-x11"
path = "src/bin/rwr-x11.rs"

[[bin]]
name = "rwr-flamewm-demo"
path = "src/bin/rwr-flamewm-demo.rs"
