[package]
name = "flamewm-x11-canary"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "flamewm-x11-canary"
path = "src/main.rs"

[dependencies]
x11rb = { workspace = true, features = ["xtest"] }

[lints]
workspace = true
