[package]
name = "flamewm-shell"
version.workspace = true
edition = "2021"
rust-version = "1.70"
license.workspace = true
repository.workspace = true

[dependencies]
chrono = "=0.4.45"
flamewm-api = { path = "../flamewm-api" }
flamewm-control-core = { path = "../flamewm-control-core" }
flamewm-control-dbus = { path = "../flamewm-control-dbus" }
flamewm-control-wire = { path = "../flamewm-control-wire" }
flamewm-dbus-reactor = { path = "../flamewm-dbus-reactor" }
flamewm-integrations-linux = { path = "../flamewm-integrations-linux" }
flamewm-platform = { path = "../flamewm-platform" }
flamewm-profiler = { path = "../flamewm-profiler" }
flamewm-reactor = { path = "../flamewm-reactor" }
flamewm-debug = { path = "../flamewm-debug" }
flamewm-shell-core = { path = "../flamewm-shell-core" }
flamewm-ui-core = { path = "../flamewm-ui-core" }
flamewm-ui-x11 = { path = "../flamewm-ui-x11" }
calloop.workspace = true
rustix = { workspace = true }

[build-dependencies]
flamewm-render-compiler = { path = "../flamewm-render-compiler" }

[lints]
workspace = true
