[package]
name = "creamui-jsx"
description = "Runtime component protocol used by creamui-macros"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
readme = "README.md"
keywords = ["jsx", "gui", "ui", "widgets"]
categories = ["gui"]

[dependencies]
creamui-core = { workspace = true }
