// flamewm-session — Flame session wrapper per C-BUILD-02 / C-BG-01
// Ensures $XDG_CONFIG_HOME/flamewm/engine-preferences exists (fixed defaults
// + Flame settings), then execs upstream
// icewm-session --icewm=<BINDIR>/flamewm --config=<engine-prefs> --theme=flamewm/default.theme
// C++11, no shell.

#include <string>
#include <sstream>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cerrno>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#include <limits.h>
#include <X11/Xcursor/Xcursor.h>

namespace {

std::string xdgConfigHome() {
    const char* xdg = getenv("XDG_CONFIG_HOME");
    if (xdg && xdg[0] != '\0') return std::string(xdg);
    const char* home = getenv("HOME");
    if (home && home[0] != '\0') return std::string(home) + "/.config";
    return std::string("/tmp");
}

std::string enginePrefsPath() {
    return xdgConfigHome() + "/flamewm/engine-preferences";
}

std::string bindirFromArgv0(const char* argv0) {
    if (!argv0 || argv0[0] == '\0') return std::string("/usr/bin");
    std::string s(argv0);
    size_t slash = s.rfind('/');
    if (slash == std::string::npos) return std::string("/usr/bin");
    std::string dir = s.substr(0, slash);
    if (dir.empty()) dir = ".";
    // Canonicalize if possible via realpath (best-effort)
    char rp[PATH_MAX];
    if (realpath(dir.c_str(), rp) != 0) return std::string(rp);
    return dir;
}

bool pathExists(const std::string& p) {
    struct stat st;
    return stat(p.c_str(), &st) == 0;
}

bool ensureDir(const std::string& dir) {
    if (dir.empty()) return false;
    if (pathExists(dir)) return true;
    // mkdir -p
    std::string cur;
    if (!dir.empty() && dir[0] == '/') cur = "/";
    std::istringstream iss(dir);
    std::string part;
    // manual split by '/'
    size_t start = (dir[0] == '/' ? 1 : 0);
    while (start <= dir.size()) {
        size_t slash = dir.find('/', start);
        std::string seg;
        if (slash == std::string::npos) seg = dir.substr(start);
        else seg = dir.substr(start, slash - start);
        if (!seg.empty()) {
            if (!cur.empty() && cur[cur.size()-1] != '/') cur += "/";
            cur += seg;
            if (!pathExists(cur)) {
                if (mkdir(cur.c_str(), 0755) != 0 && errno != EEXIST) return false;
            }
        }
        if (slash == std::string::npos) break;
        start = slash + 1;
    }
    return pathExists(dir);
}

std::string dirName(const std::string& p) {
    size_t slash = p.rfind('/');
    if (slash == std::string::npos) return std::string(".");
    if (slash == 0) return std::string("/");
    return p.substr(0, slash);
}

std::string cursorThemePath(const std::string& bindir) {
    return dirName(bindir) + "/share/icewm/flamewm/cursors";
}

bool configureCursorEnvironment(const std::string& bindir) {
    if (getenv("XCURSOR_THEME") == 0 && setenv("XCURSOR_THEME", "Breeze", 1) != 0) {
        fprintf(stderr, "flamewm-session: cannot set XCURSOR_THEME: %s\n", strerror(errno));
        return false;
    }
    if (getenv("XCURSOR_SIZE") == 0 && setenv("XCURSOR_SIZE", "24", 1) != 0) {
        fprintf(stderr, "flamewm-session: cannot set XCURSOR_SIZE: %s\n", strerror(errno));
        return false;
    }
    if (getenv("XCURSOR_THEME_CORE") == 0 && setenv("XCURSOR_THEME_CORE", "1", 1) != 0) {
        fprintf(stderr, "flamewm-session: cannot set XCURSOR_THEME_CORE: %s\n", strerror(errno));
        return false;
    }

    std::string path = cursorThemePath(bindir);
    const char* existing = getenv("XCURSOR_PATH");
    if (existing && existing[0] != '\0') {
        path += ":";
        path += existing;
    } else {
        const char* libraryPath = XcursorLibraryPath();
        if (libraryPath && libraryPath[0] != '\0') {
            path += ":";
            path += libraryPath;
        }
    }
    if (setenv("XCURSOR_PATH", path.c_str(), 1) != 0) {
        fprintf(stderr, "flamewm-session: cannot set XCURSOR_PATH: %s\n", strerror(errno));
        return false;
    }
    return true;
}

// Generate the engine-owned defaults. Flame settings do not expose a
// source-proven mapping to these engine preferences.
std::string buildEnginePrefsDefaults() {
    std::ostringstream oss;
    oss << "# FlameWM engine preferences — generated by flamewm-session\n";
    oss << "Look=flat\n";
    oss << "ShowTaskBar=0\n";
    oss << "TaskBarShowClock=0\n";
    oss << "TaskBarShowAPMStatus=0\n";
    oss << "TaskBarShowAPMAuto=0\n";
    oss << "TaskBarShowAPMTime=0\n";
    oss << "TaskBarShowAPMGraph=0\n";
    oss << "TaskBarShowMailboxStatus=0\n";
    oss << "TaskBarShowWorkspaces=0\n";
    oss << "TaskBarShowWindows=0\n";
    oss << "TaskBarShowShowDesktopButton=0\n";
    oss << "TaskBarShowTray=0\n";
    oss << "TaskBarShowTransientWindows=0\n";
    oss << "TaskBarShowAllWindows=0\n";
    oss << "TaskBarShowWindowIcons=0\n";
    oss << "TaskBarShowWindowTitles=0\n";
    oss << "TaskBarShowStartMenu=0\n";
    oss << "TaskBarShowWindowListMenu=0\n";
    oss << "TaskBarShowCPUStatus=0\n";
    oss << "TaskBarShowMEMStatus=0\n";
    oss << "TaskBarShowNetStatus=0\n";
    oss << "TaskBarShowCollapseButton=0\n";
    oss << "ShowWorkspaceStatus=0\n";
    oss << "QuickSwitch=1\n";
    oss << "QuickSwitchPreview=1\n";
    oss << "QuickSwitchVertical=0\n";
    oss << "QuickSwitchFillSelection=1\n";
    oss << "DesktopBackgroundImage=\"flamewm-wallpaper.webp\"\n";
    oss << "DesktopBackgroundCenter=1\n";
    oss << "DesktopBackgroundScaled=1\n";
    oss << "DesktopBackgroundColor=\"#000000\"\n";
    return oss.str();
}

bool ensureEnginePrefs() {
    std::string ep = enginePrefsPath();
    std::string dir = dirName(ep);
    if (!ensureDir(dir)) {
        fprintf(stderr, "flamewm-session: cannot create %s: %s\n", dir.c_str(), strerror(errno));
        return false;
    }
    std::string tmp = ep + ".tmp." + std::to_string(static_cast<long long>(getpid()));
    std::string data = buildEnginePrefsDefaults();
    FILE* f = fopen(tmp.c_str(), "wb");
    if (!f) {
        fprintf(stderr, "flamewm-session: cannot open %s: %s\n", tmp.c_str(), strerror(errno));
        return false;
    }
    size_t w = fwrite(data.data(), 1, data.size(), f);
    if (w != data.size()) {
        fclose(f);
        unlink(tmp.c_str());
        fprintf(stderr, "flamewm-session: write failed %s\n", tmp.c_str());
        return false;
    }
    if (fflush(f) != 0) {
        fclose(f);
        unlink(tmp.c_str());
        fprintf(stderr, "flamewm-session: flush failed %s: %s\n", tmp.c_str(), strerror(errno));
        return false;
    }
    if (fclose(f) != 0) {
        unlink(tmp.c_str());
        fprintf(stderr, "flamewm-session: close failed %s: %s\n", tmp.c_str(), strerror(errno));
        return false;
    }
    if (rename(tmp.c_str(), ep.c_str()) != 0) {
        unlink(tmp.c_str());
        fprintf(stderr, "flamewm-session: rename %s -> %s: %s\n", tmp.c_str(), ep.c_str(), strerror(errno));
        return false;
    }
    return true;
}

} // namespace

int main(int argc, char** argv) {
    // 1) Ensure engine-preferences exists before exec
    if (!ensureEnginePrefs()) {
        fprintf(stderr, "flamewm-session: cannot generate engine-preferences; aborting session\n");
        return 1;
    }
    std::string ep = enginePrefsPath();
    std::string bindir = bindirFromArgv0(argc > 0 ? argv[0] : 0);
    if (!configureCursorEnvironment(bindir)) return 1;
    std::string flamewmBin = bindir + "/flamewm";
    // Resolve icewm-session upstream binary: sibling icewm-session, fallback to PATH
    std::string sessionBin = bindir + "/icewm-session";
    if (!pathExists(sessionBin)) {
        sessionBin = "icewm-session";
    }

    // If flamewm binary not at bindir/flamewm, fall back to icewm (should not happen in install)
    if (!pathExists(flamewmBin)) {
        // Try PATH lookup for flamewm, else keep as-is (exec will fail visibly)
    }
    // 2) Exec upstream icewm-session; it is the sole desktop supervisor owner.
    // Build argv: icewm-session --icewm=<flamewmBin> --config=<ep> --theme=flamewm/default.theme [passthrough display/sync/etc]
    // Preserve relevant passthrough: --display, --sync, --replace, --notray, --nobg, --sound, --output, --alpha, --valgrind, --catchsegv
    // Simple: forward all original args except argv[0]; icewm-session supervises desktop.

    // Count original args to forward
    int origExtra = (argc > 1) ? (argc - 1) : 0;
    // We add 3: --icewm, --config, --theme
    int total = 1 + 3 + origExtra + 1;
    char** execArgs = new char*[total];
    int idx = 0;
    std::string icewmArg = std::string("--icewm=") + flamewmBin;
    std::string configArg = std::string("--config=") + ep;
    std::string themeArg = std::string("--theme=flamewm/default.theme");

    execArgs[idx++] = const_cast<char*>(sessionBin.c_str());
    execArgs[idx++] = const_cast<char*>(icewmArg.c_str());
    execArgs[idx++] = const_cast<char*>(configArg.c_str());
    execArgs[idx++] = const_cast<char*>(themeArg.c_str());
    for (int i = 1; i < argc; ++i) {
        // Avoid duplicating --icewm/--config/--theme if caller already passed them
        std::string a(argv[i] ? argv[i] : "");
        if (a.compare(0, 8, "--icewm=") == 0) continue;
        if (a.compare(0, 9, "--config=") == 0) continue;
        if (a.compare(0, 8, "--theme=") == 0) continue;
        if (a == "--icewm" || a == "-i" || a == "--config" || a == "-c" || a == "--theme" || a == "-t") {
            // Skip flag + its value
            if (i + 1 < argc) ++i;
            continue;
        }
        execArgs[idx++] = argv[i];
    }
    execArgs[idx] = 0;

    execvp(sessionBin.c_str(), execArgs);
    int execErr = errno;
    fprintf(stderr, "flamewm-session: exec %s failed: %s\n", sessionBin.c_str(), strerror(execErr));
    delete[] execArgs;
    return 127;
}
